import subprocess
import csv
from io import StringIO

print("<!-- This file was generated by hack/generate-list-docs.py -->")

print("| ID | Target | Description |")
print("|----|--------|-------------|")

listAsCSV = subprocess.getoutput("kube-score list")

for row in csv.reader(StringIO(listAsCSV)):
    print("| " + " | ".join(row) + " | ")
