builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
dockers:
  - image: zegl/kube-score
    goos: linux
    goarch: amd64
    binary: kube-score
    skip_push: true
    dockerfile: Dockerfile
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
